### ISSUE TITLE
error when compiling the wallet in ubuntu 16.04

### ISSUE THREAD

**Issue by bouguerra12** [deftchain/deft#1]
hello dev ,i got error when trying to compile  the wallet in ubuntu 16.04

 

> make[3]: Entering directory '/home/med/Desktop/deft/deft-0.15.1/src/secp256k1'
> make[3]: Leaving directory '/home/med/Desktop/deft/deft-0.15.1/src/secp256k1'
>   CXXLD    deftd
> /usr/bin/ld: libbitcoin_consensus.a(libbitcoin_consensus_a-balloon.o): relocation R_X86_64_PC32 against undefined symbol `SHA256_Init@@OPENSSL_1.0.0' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: Bad value
> collect2: error: ld returned 1 exit status
> Makefile:3641: recipe for target 'deftd' failed
> make[2]: *** [deftd] Error 1
> make[2]: Leaving directory '/home/med/Desktop/deft/deft-0.15.1/src'
> Makefile:9324: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/med/Desktop/deft/deft-0.15.1/src'
> Makefile:747: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1

can you please help me ? 

thank you

**Comment by deftchain** [comment]
thankyou for the bug report; i am able to reproduce the issue on ubuntu 16.04, but not on my development system (debian 9.4).
however, this is a valid issue that did pop up while testing balloon hashing some time back. i will have an answer/workaround for you in the next few hours.

appreciated,
james

**Comment by deftchain** [comment]
it seems the issue is limited to ubuntu 16.04, or some odd versioning combination that has occurred in that release. moving up to ubuntu 18.04 purely to test; could not replicate the issue:

```
apt update
apt install build-essential autoconf automake libssl1.0-dev libdb5.3-dev libdb5.3++-dev libtool libevent-dev pkg-config
add-apt-repository universe
apt-get update
apt-get install libboost-all-dev
git clone http://github.com/deftchain/deft
cd deft/
./autogen.sh
./configure --with-incompatible-bdb --disable-tests
make -j4
```

aside from needing to pull libboost from the repository 'universe'; the installation/compilation steps are almost identical to debian.

**Comment by deftchain** [comment]
environment

**Comment by deftchain** [comment]
hey mate can you try a 'git pull' followed by 'make', ive tested a patch (https://github.com/deftchain/deft/commit/bb133494e6a72b299dbd93e2cd5353b0519200fe) against another ubuntu 16.04 vps, seems to resolve the issue..
